name: wake
version: '${version}'

main: dev.muggel.wake.Wake
api-version: '1.21'
load: POSTWORLD

authors: [muggel]
website: https://muggel.dev
softdepend: [AxiomPaper]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.46.0.0
  - org.mariadb.jdbc:mariadb-java-client:3.4.0
  - io.lettuce:lettuce-core:6.8.2.RELEASE